### ISSUE TITLE
Como subir la aplicación

### ISSUE THREAD

**Issue by rodolforeinafigueroa** [AndresArana/TelephoneDirectory#1]
Buenos días Andres,

Puedes por favor crear un archivo de texto (README.md) donde expliques como se debe probar el programa, veo que tienes dos3 proyectos, cuales se deben subir y en que orden.

Quedo atento. 

Gracias

**Comment by AndresArana** [comment]
Vale, si señor

**Comment by rodolforeinafigueroa** [comment]
Hola,

Por favor tambien indicame que esta funcionando y que no.

**Comment by AndresArana** [comment]
Listo Rodolfo, ya hago el commit y en el readme explico todo eso

**Comment by AndresArana** [comment]
Hola Rodolfo, ya cree el readme de como ejecutar el proyecto, que tiene el
proyecto y lo que me falta por implementar, en el transcurso de este día
haré otro commit ya que me falta refactorizar algunas partes del codigo que
pueden mejorar y poder aplicar el principio 1 de solid, quedo atento, buen
día

**Comment by rodolforeinafigueroa** [comment]
Quedo atento para cerrar este issue
